"""
Sanskrit lexicon for word-by-word gloss backfill.

Maps IAST surface forms (as they appear in our corpus IAST lines, sandhi-stripped
to the extent the tokenizer can manage) to (gloss_en, lemma_iast, morph).

This is a conservative, curated lexicon — only entries the editor is confident
about. Unknown tokens are skipped (and the backfiller falls back to the
existing gloss list for that verse).

Keys are normalized: lowercase, no leading/trailing punctuation, NFC-normalized.
"""

from __future__ import annotations
import unicodedata
import re

def norm(s: str) -> str:
    s = unicodedata.normalize("NFC", s)
    s = s.strip().lower()
    # strip trailing punctuation but keep internal hyphens
    s = re.sub(r"^[\|\.\,\;\:\!\?\'\"\(\)\[\]]+|[\|\.\,\;\:\!\?\'\"\(\)\[\]]+$", "", s)
    return s


# Each entry: (gloss_en, lemma_iast, morph)
# morph may be None or short tag like "nom. sg. m.", "loc. sg. n.", "adv.", "3sg. pres."
_RAW: dict[str, tuple[str, str, str | None]] = {
    # --- pronouns & demonstratives ---
    "tat": ("that", "tad", "nom./acc. sg. n."),
    "tat tu": ("that, however", "tad", "nom. sg. n. + ptcl."),
    "tad": ("that", "tad", "nom./acc. sg. n."),
    "tad vat": ("like that", "tadvat", "adv."),
    "tadvat": ("like that", "tadvat", "adv."),
    "tasya": ("of that, of him", "tad", "gen. sg. m./n."),
    "tasmin": ("in that", "tad", "loc. sg. m./n."),
    "tasmāt": ("from that, therefore", "tad", "abl. sg. m./n."),
    "tena": ("by that, by him", "tad", "inst. sg. m./n."),
    "tatra": ("there, in that", "tatra", "adv."),
    "tatra tatra": ("there, in every such place", "tatra", "adv. correlative"),
    "te": ("they; to/for you", "tad/tvad", "nom. pl. m. / dat.gen. sg."),
    "taiḥ": ("by those", "tad", "inst. pl. m./n."),
    "teṣām": ("of those", "tad", "gen. pl. m./n."),
    "sa": ("he, that one", "tad", "nom. sg. m."),
    "saḥ": ("he, that one", "tad", "nom. sg. m."),
    "sā": ("she, that one", "tad", "nom. sg. f."),
    "tām": ("her, that (f.)", "tad", "acc. sg. f."),
    "tāḥ": ("them, those (f.)", "tad", "acc. pl. f."),
    "tāni": ("those (n.)", "tad", "nom./acc. pl. n."),
    "ime": ("these", "idam", "nom. pl. m."),
    "idam": ("this", "idam", "nom./acc. sg. n."),
    "iyam": ("this (f.)", "idam", "nom. sg. f."),
    "ayam": ("this (m.)", "idam", "nom. sg. m."),
    "asya": ("of this", "idam", "gen. sg. m./n."),
    "asmin": ("in this", "idam", "loc. sg. m./n."),
    "asmāt": ("from this", "idam", "abl. sg. m./n."),
    "anena": ("by this", "idam", "inst. sg. m./n."),
    "etat": ("this", "etad", "nom./acc. sg. n."),
    "etad": ("this", "etad", "nom./acc. sg. n."),
    "eṣa": ("this one (m.)", "etad", "nom. sg. m."),
    "eṣā": ("this one (f.)", "etad", "nom. sg. f."),
    "yat": ("which, what", "yad", "nom./acc. sg. n. rel."),
    "yad": ("which, what", "yad", "nom./acc. sg. n. rel."),
    "yo": ("who", "yad", "nom. sg. m. rel."),
    "yaḥ": ("who", "yad", "nom. sg. m. rel."),
    "yā": ("who/which (f.)", "yad", "nom. sg. f. rel."),
    "yasya": ("of whom, whose", "yad", "gen. sg. m./n. rel."),
    "yasmin": ("in whom/which", "yad", "loc. sg. m./n. rel."),
    "yathā": ("as, in the way that", "yathā", "adv. rel."),
    "tathā": ("thus, in that way", "tathā", "adv."),
    "yatra": ("where, wherever", "yatra", "adv. rel."),
    "yatra yatra": ("wherever", "yatra", "adv. correlative"),
    "yāvat": ("as long as, until", "yāvat", "adv. rel."),
    "tāvat": ("so long, then", "tāvat", "adv."),
    "kva": ("where", "kva", "interrog. adv."),
    "kutaḥ": ("from where, why", "kutas", "interrog. adv."),
    "kim": ("what", "kim", "interrog. nom./acc. sg. n."),
    "ko": ("who", "kim", "interrog. nom. sg. m."),
    "kaḥ": ("who", "kim", "interrog. nom. sg. m."),
    "kā": ("who (f.)", "kim", "interrog. nom. sg. f."),
    "kasya": ("whose", "kim", "interrog. gen. sg. m./n."),
    "katham": ("how", "katham", "interrog. adv."),
    "ahaṃ": ("I", "asmad", "nom. sg."),
    "ahaṁ": ("I", "asmad", "nom. sg."),
    "aham": ("I", "asmad", "nom. sg."),
    "mama": ("my, of me", "asmad", "gen. sg."),
    "me": ("my, to me", "asmad", "gen./dat. sg. encl."),
    "mayā": ("by me", "asmad", "inst. sg."),
    "mayi": ("in me", "asmad", "loc. sg."),
    "mām": ("me", "asmad", "acc. sg."),
    "tvam": ("you", "tvad", "nom. sg."),
    "tvaṃ": ("you", "tvad", "nom. sg."),
    "tvaṁ": ("you", "tvad", "nom. sg."),
    "tava": ("your, of you", "tvad", "gen. sg."),
    "tvayā": ("by you", "tvad", "inst. sg."),
    "tvayi": ("in you", "tvad", "loc. sg."),
    "tvām": ("you (acc.)", "tvad", "acc. sg."),
    "ātmā": ("the Self", "ātman", "nom. sg. m."),
    "ātman": ("the Self", "ātman", "stem"),
    "ātmanaḥ": ("of the Self", "ātman", "gen. sg. m."),
    "ātmani": ("in the Self", "ātman", "loc. sg. m."),
    "ātmānam": ("the Self (acc.)", "ātman", "acc. sg. m."),

    # --- particles, conjunctions, indeclinables ---
    "ca": ("and", "ca", "conj."),
    "vā": ("or", "vā", "conj."),
    "tu": ("but, however", "tu", "ptcl."),
    "api": ("also, even", "api", "ptcl."),
    "'pi": ("also, even", "api", "ptcl. (sandhi)"),
    "hi": ("indeed, for", "hi", "ptcl."),
    "eva": ("only, indeed, very", "eva", "ptcl. emphatic"),
    "iva": ("like, as if", "iva", "ptcl."),
    "na": ("not", "na", "negation"),
    "no": ("not", "na", "negation"),
    "mā": ("do not (prohibitive)", "mā", "prohibitive"),
    "iti": ("thus, end-quote", "iti", "ptcl."),
    "khalu": ("indeed, certainly", "khalu", "ptcl."),
    "atha": ("now, then", "atha", "ptcl."),
    "athavā": ("or else", "athavā", "conj."),
    "tarhi": ("then, in that case", "tarhi", "adv."),
    "saha": ("with, together with", "saha", "indecl."),
    "sahaja": ("innate, natural", "sahaja", "adj."),
    "punaḥ": ("again", "punar", "adv."),
    "punar": ("again", "punar", "adv."),
    "sadā": ("always", "sadā", "adv."),
    "sarvadā": ("always, at all times", "sarvadā", "adv."),
    "nityam": ("perpetually, eternally", "nitya", "adv. / acc. n."),
    "nitya": ("eternal", "nitya", "adj."),
    "nityaḥ": ("eternal", "nitya", "nom. sg. m."),
    "śaśvat": ("perpetually", "śaśvat", "adv."),
    "kadācit": ("at any time, ever", "kadācit", "indef. adv."),
    "kvacit": ("anywhere", "kvacit", "indef. adv."),
    "kutracit": ("anywhere", "kutracit", "indef. adv."),
    "kutracana": ("anywhere", "kutracana", "indef. adv."),
    "evam": ("thus, in this way", "evam", "adv."),
    "evaṃ": ("thus, in this way", "evam", "adv."),
    "evaṁ": ("thus, in this way", "evam", "adv."),
    "ataḥ": ("from this, therefore", "atas", "adv."),
    "atas": ("from this, therefore", "atas", "adv."),
    "tasmāt": ("therefore, from that", "tad", "abl. sg."),
    "samyak": ("rightly, correctly", "samyak", "adv."),
    "asti": ("is, exists", "as", "3sg. pres."),
    "syāt": ("would be", "as", "3sg. opt."),
    "santi": ("they are", "as", "3pl. pres."),
    "bhavet": ("would be, may become", "bhū", "3sg. opt."),
    "bhavati": ("becomes, is", "bhū", "3sg. pres."),
    "bhavanti": ("they become, are", "bhū", "3pl. pres."),
    "babhūva": ("became, was", "bhū", "3sg. pf."),
    "bhūtvā": ("having become", "bhū", "gerund"),

    # --- key Trika / Śaiva vocabulary ---
    "śiva": ("Śiva, the auspicious one", "śiva", "stem"),
    "śivaḥ": ("Śiva", "śiva", "nom. sg. m."),
    "śivam": ("Śiva (acc.); auspicious", "śiva", "acc. sg. m./n."),
    "śivasya": ("of Śiva", "śiva", "gen. sg. m."),
    "śive": ("in Śiva; O Śive", "śiva", "loc. sg. / voc. f."),
    "śivā": ("the Goddess; auspicious (f.)", "śivā", "nom. sg. f."),
    "śaktiḥ": ("Power, Śakti", "śakti", "nom. sg. f."),
    "śakti": ("Power, Śakti", "śakti", "stem"),
    "śaktyā": ("by Power, by Śakti", "śakti", "inst. sg. f."),
    "śakteḥ": ("of Power, of Śakti", "śakti", "gen./abl. sg. f."),
    "śaktīnām": ("of the powers", "śakti", "gen. pl. f."),
    "bhairava": ("Bhairava", "bhairava", "stem"),
    "bhairavaḥ": ("Bhairava", "bhairava", "nom. sg. m."),
    "bhairave": ("in Bhairava; O Bhairava", "bhairava", "loc. sg. / voc."),
    "bhairavī": ("Bhairavī, the Goddess", "bhairavī", "nom. sg. f."),
    "devī": ("the Goddess", "devī", "nom. sg. f."),
    "devi": ("O Goddess", "devī", "voc. sg. f."),
    "deva": ("O Lord, god", "deva", "voc. / stem"),
    "devaḥ": ("the god, the Lord", "deva", "nom. sg. m."),
    "devasya": ("of the god", "deva", "gen. sg. m."),
    "īśvara": ("Lord, ruler", "īśvara", "stem"),
    "īśvaraḥ": ("the Lord", "īśvara", "nom. sg. m."),
    "parameśvara": ("Supreme Lord", "parameśvara", "voc./nom. sg. m."),
    "para": ("supreme, highest, other", "para", "adj. stem"),
    "paraḥ": ("supreme", "para", "nom. sg. m."),
    "param": ("supreme; beyond", "para", "acc. sg. n./m."),
    "parā": ("supreme (f.); the supreme Goddess", "parā", "nom. sg. f."),
    "parāyāḥ": ("of the supreme (f.)", "parā", "gen./abl. sg. f."),
    "paratvam": ("supremacy, the state of being supreme", "paratva", "nom./acc. sg. n."),
    "paramam": ("the supreme", "parama", "acc. sg. n."),
    "paramaḥ": ("supreme", "parama", "nom. sg. m."),
    "paramā": ("supreme (f.)", "parama", "nom. sg. f."),
    "citi": ("Consciousness", "citi", "stem"),
    "citiḥ": ("Consciousness", "citi", "nom. sg. f."),
    "cit": ("pure Consciousness", "cit", "stem"),
    "citta": ("mind, mind-stuff", "citta", "stem"),
    "cittam": ("the mind", "citta", "nom./acc. sg. n."),
    "cetanā": ("awareness, sentience", "cetanā", "nom. sg. f."),
    "caitanyam": ("pure consciousness, sentience", "caitanya", "nom. sg. n."),
    "caitanya": ("pure consciousness", "caitanya", "stem"),
    "saṃvit": ("Awareness, Consciousness", "saṃvid", "nom. sg. f."),
    "saṃvid": ("Awareness", "saṃvid", "stem"),
    "saṃvedana": ("awareness, experience", "saṃvedana", "stem"),
    "spanda": ("vibration, pulsation", "spanda", "stem"),
    "spandaḥ": ("vibration, spanda", "spanda", "nom. sg. m."),
    "spandena": ("by vibration", "spanda", "inst. sg. m."),
    "spandaḥ": ("the pulsation", "spanda", "nom. sg. m."),

    # mind / body / senses
    "manaḥ": ("the mind", "manas", "nom./acc. sg. n."),
    "manas": ("the mind", "manas", "stem"),
    "manasā": ("by the mind", "manas", "inst. sg. n."),
    "manasi": ("in the mind", "manas", "loc. sg. n."),
    "buddhi": ("intellect", "buddhi", "stem"),
    "buddhiḥ": ("the intellect", "buddhi", "nom. sg. f."),
    "buddhyā": ("by the intellect", "buddhi", "inst. sg. f."),
    "ahaṅkāra": ("ego, I-maker", "ahaṅkāra", "stem"),
    "indriya": ("sense-organ", "indriya", "stem"),
    "indriyāṇi": ("the senses", "indriya", "nom./acc. pl. n."),
    "prāṇa": ("breath, vital force", "prāṇa", "stem"),
    "prāṇaḥ": ("the breath", "prāṇa", "nom. sg. m."),
    "prāṇena": ("by the breath", "prāṇa", "inst. sg. m."),
    "prāṇāḥ": ("the vital airs", "prāṇa", "nom. pl. m."),
    "apāna": ("down-breath", "apāna", "stem"),
    "apānaḥ": ("the down-breath", "apāna", "nom. sg. m."),
    "udāna": ("up-breath", "udāna", "stem"),
    "deha": ("body", "deha", "stem"),
    "dehaḥ": ("the body", "deha", "nom. sg. m."),
    "dehe": ("in the body", "deha", "loc. sg. m."),
    "śarīra": ("body", "śarīra", "stem"),
    "śarīram": ("body", "śarīra", "nom./acc. sg. n."),
    "hṛdaya": ("heart", "hṛdaya", "stem"),
    "hṛdayam": ("the heart", "hṛdaya", "nom./acc. sg. n."),
    "hṛdi": ("in the heart", "hṛdaya", "loc. sg. n."),
    "cakṣus": ("the eye", "cakṣus", "stem"),
    "cakṣuḥ": ("the eye", "cakṣus", "nom. sg. n."),
    "netra": ("eye", "netra", "stem"),
    "netre": ("the two eyes", "netra", "nom. du. n."),
    "kāya": ("body", "kāya", "stem"),

    # space / time
    "ākāśa": ("space, ether", "ākāśa", "stem"),
    "ākāśe": ("in space", "ākāśa", "loc. sg. m./n."),
    "vyoman": ("sky, void", "vyoman", "stem"),
    "vyomni": ("in the void", "vyoman", "loc. sg. n."),
    "kāla": ("time", "kāla", "stem"),
    "kālaḥ": ("time", "kāla", "nom. sg. m."),
    "kāle": ("at the time", "kāla", "loc. sg. m."),
    "diś": ("direction", "diś", "stem"),
    "diśaḥ": ("the directions", "diś", "nom./acc. pl. f."),

    # world / reality / categories
    "jagat": ("the world", "jagat", "nom./acc. sg. n."),
    "jagataḥ": ("of the world", "jagat", "gen./abl. sg. n."),
    "loka": ("world, people", "loka", "stem"),
    "lokaḥ": ("the world", "loka", "nom. sg. m."),
    "viśva": ("the universe, all", "viśva", "stem"),
    "viśvam": ("the universe", "viśva", "nom./acc. sg. n."),
    "viśvasya": ("of the universe", "viśva", "gen. sg. m./n."),
    "sarva": ("all, every", "sarva", "adj. stem"),
    "sarvam": ("all, everything", "sarva", "nom./acc. sg. n."),
    "sarve": ("all (m. pl.)", "sarva", "nom. pl. m."),
    "sarvāḥ": ("all (f. pl.)", "sarva", "nom. pl. f."),
    "sarvāṇi": ("all (n. pl.)", "sarva", "nom./acc. pl. n."),
    "sarvataḥ": ("on all sides, everywhere", "sarvatas", "adv."),
    "sarvatra": ("everywhere", "sarvatra", "adv."),
    "tattva": ("reality, category, principle", "tattva", "stem"),
    "tattvam": ("the reality", "tattva", "nom./acc. sg. n."),
    "tattvataḥ": ("in reality", "tattvatas", "adv."),
    "tattvato": ("in reality", "tattvatas", "adv."),
    "māyā": ("illusion, the limiting principle", "māyā", "nom. sg. f."),
    "māyāyāḥ": ("of māyā", "māyā", "gen./abl. sg. f."),
    "prakṛti": ("primal nature, material principle", "prakṛti", "stem"),
    "prakṛtiḥ": ("primal nature", "prakṛti", "nom. sg. f."),
    "puruṣa": ("the soul, person", "puruṣa", "stem"),
    "puruṣaḥ": ("the soul, the person", "puruṣa", "nom. sg. m."),
    "kalā": ("limited agency, art, phase", "kalā", "nom. sg. f."),
    "kalāḥ": ("the kalās", "kalā", "nom./acc. pl. f."),

    # knowledge / ignorance / liberation
    "jñāna": ("knowledge, wisdom", "jñāna", "stem"),
    "jñānam": ("knowledge", "jñāna", "nom./acc. sg. n."),
    "jñānena": ("by knowledge", "jñāna", "inst. sg. n."),
    "jñānāt": ("from knowledge", "jñāna", "abl. sg. n."),
    "jñātā": ("the knower", "jñātṛ", "nom. sg. m."),
    "jñeyam": ("the knowable, object of knowledge", "jñeya", "nom./acc. sg. n."),
    "ajñāna": ("ignorance, non-knowledge", "ajñāna", "stem"),
    "ajñānam": ("ignorance", "ajñāna", "nom./acc. sg. n."),
    "vidyā": ("knowledge", "vidyā", "nom. sg. f."),
    "avidyā": ("nescience, ignorance", "avidyā", "nom. sg. f."),
    "bandha": ("bondage", "bandha", "stem"),
    "bandhaḥ": ("bondage", "bandha", "nom. sg. m."),
    "mokṣa": ("liberation", "mokṣa", "stem"),
    "mokṣaḥ": ("liberation", "mokṣa", "nom. sg. m."),
    "mukta": ("liberated", "mukta", "ppp. stem"),
    "muktaḥ": ("liberated", "mukta", "nom. sg. m."),
    "muktiḥ": ("liberation", "mukti", "nom. sg. f."),
    "siddhi": ("attainment, accomplishment", "siddhi", "stem"),
    "siddhiḥ": ("attainment", "siddhi", "nom. sg. f."),
    "yoga": ("yoga, union", "yoga", "stem"),
    "yogaḥ": ("yoga", "yoga", "nom. sg. m."),
    "yogī": ("the yogin", "yogin", "nom. sg. m."),
    "yogin": ("yogin", "yogin", "stem"),
    "yoginaḥ": ("of the yogin; the yogins", "yogin", "gen. sg. / nom. pl. m."),
    "yoginaṃ": ("the yogin (acc.)", "yogin", "acc. sg. m."),
    "guru": ("teacher", "guru", "stem"),
    "guruḥ": ("the teacher", "guru", "nom. sg. m."),
    "guroḥ": ("of the teacher", "guru", "gen./abl. sg. m."),

    # mantra / sound / speech
    "śabda": ("sound, word", "śabda", "stem"),
    "śabdaḥ": ("sound, word", "śabda", "nom. sg. m."),
    "vāc": ("speech", "vāc", "stem"),
    "vāk": ("speech", "vāc", "nom. sg. f."),
    "vācā": ("by speech", "vāc", "inst. sg. f."),
    "vācaḥ": ("of speech", "vāc", "gen. sg. f."),
    "nāda": ("sound, resonance", "nāda", "stem"),
    "nādaḥ": ("the sound", "nāda", "nom. sg. m."),
    "bindu": ("point, drop", "bindu", "stem"),
    "binduḥ": ("the point, the bindu", "bindu", "nom. sg. m."),
    "mantra": ("mantra", "mantra", "stem"),
    "mantraḥ": ("the mantra", "mantra", "nom. sg. m."),
    "varṇa": ("phoneme, letter, color, class", "varṇa", "stem"),
    "varṇāḥ": ("phonemes, letters", "varṇa", "nom. pl. m."),
    "akṣara": ("syllable, the imperishable", "akṣara", "stem"),
    "akṣaram": ("the syllable, the imperishable", "akṣara", "nom./acc. sg. n."),

    # form / nature
    "rūpa": ("form", "rūpa", "stem"),
    "rūpam": ("the form", "rūpa", "nom./acc. sg. n."),
    "rūpeṇa": ("by/as form", "rūpa", "inst. sg. n."),
    "svarūpa": ("own nature, essential form", "svarūpa", "stem"),
    "svarūpam": ("own essential nature", "svarūpa", "nom./acc. sg. n."),
    "svabhāva": ("own being, nature", "svabhāva", "stem"),
    "svabhāvaḥ": ("own nature", "svabhāva", "nom. sg. m."),
    "svātantrya": ("autonomy, freedom", "svātantrya", "stem"),
    "svātantryam": ("autonomy", "svātantrya", "nom./acc. sg. n."),
    "icchā": ("will, desire", "icchā", "nom. sg. f."),
    "icchayā": ("by will, by desire", "icchā", "inst. sg. f."),
    "krīḍā": ("play, sport", "krīḍā", "nom. sg. f."),
    "līlā": ("play, divine sport", "līlā", "nom. sg. f."),
    "ānanda": ("bliss", "ānanda", "stem"),
    "ānandaḥ": ("bliss", "ānanda", "nom. sg. m."),
    "ānandena": ("by bliss", "ānanda", "inst. sg. m."),
    "sukha": ("happiness, ease", "sukha", "stem"),
    "sukham": ("happiness; comfortably", "sukha", "nom./acc. sg. n."),
    "duḥkha": ("suffering", "duḥkha", "stem"),
    "duḥkham": ("suffering", "duḥkha", "nom./acc. sg. n."),

    # adjectives — common
    "mahā": ("great", "mahat", "stem in cpd."),
    "mahat": ("great", "mahat", "stem"),
    "mahān": ("great", "mahat", "nom. sg. m."),
    "mahatī": ("great (f.)", "mahat", "nom. sg. f."),
    "śubha": ("auspicious", "śubha", "adj. stem"),
    "śubham": ("auspicious", "śubha", "nom./acc. sg. n."),
    "uttama": ("highest, best", "uttama", "adj. stem"),
    "uttamam": ("the highest", "uttama", "nom./acc. sg. n."),
    "śuddha": ("pure", "śuddha", "ppp. stem"),
    "śuddham": ("pure", "śuddha", "nom./acc. sg. n."),
    "niścala": ("motionless, steady", "niścala", "adj."),
    "sthira": ("steady, firm", "sthira", "adj."),
    "sūkṣma": ("subtle", "sūkṣma", "adj."),
    "sthūla": ("gross", "sthūla", "adj."),
    "śūnya": ("void, empty", "śūnya", "adj. stem"),
    "śūnyam": ("the void, empty", "śūnya", "nom./acc. sg. n."),
    "śūnye": ("in the void", "śūnya", "loc. sg. n."),
    "pūrṇa": ("full, complete", "pūrṇa", "adj. stem"),
    "pūrṇam": ("full", "pūrṇa", "nom./acc. sg. n."),
    "pūrṇaḥ": ("full", "pūrṇa", "nom. sg. m."),

    # direction / inside-outside
    "bāhya": ("outer, external", "bāhya", "adj. stem"),
    "bāhye": ("outwardly, in the external", "bāhya", "loc. sg. m./n."),
    "abhyantara": ("inner, internal", "abhyantara", "adj. stem"),
    "abhyantare": ("inwardly, in the internal", "abhyantara", "loc. sg. m./n."),
    "antar": ("within, inside", "antar", "indecl."),
    "antaḥ": ("within", "antar", "indecl."),
    "madhya": ("middle", "madhya", "stem"),
    "madhye": ("in the middle", "madhya", "loc. sg. n."),
    "ūrdhva": ("upward", "ūrdhva", "stem"),
    "ūrdhvam": ("upward", "ūrdhva", "adv. / nom. n."),
    "adhaḥ": ("downward", "adhas", "indecl."),
    "agre": ("in front, ahead", "agra", "loc. sg. n."),

    # meditation / awareness verbs and nouns
    "dhāraṇā": ("concentration, holding", "dhāraṇā", "nom. sg. f."),
    "dhyāna": ("meditation", "dhyāna", "stem"),
    "dhyānam": ("meditation", "dhyāna", "nom./acc. sg. n."),
    "samādhi": ("absorption", "samādhi", "stem"),
    "samādhiḥ": ("absorption, samādhi", "samādhi", "nom. sg. m."),
    "smaraṇam": ("remembering", "smaraṇa", "nom./acc. sg. n."),
    "smaret": ("should remember/meditate on", "smṛ", "3sg. opt."),
    "cintayet": ("should contemplate", "cint", "3sg. opt."),
    "bhāvayet": ("should cultivate/contemplate", "bhū caus.", "3sg. opt."),
    "paśyet": ("should see", "dṛś", "3sg. opt."),
    "yuktaḥ": ("yoked, engaged", "yukta", "nom. sg. m."),
    "yuktā": ("yoked (f.)", "yukta", "nom. sg. f."),
    "vimṛśet": ("should reflect, recognise", "vi-mṛś", "3sg. opt."),

    # motion verbs
    "gacchati": ("goes", "gam", "3sg. pres."),
    "gacchet": ("would go", "gam", "3sg. opt."),
    "yāti": ("goes", "yā", "3sg. pres."),
    "yāsyati": ("will go, could go", "yā", "3sg. fut."),
    "āyāti": ("comes", "ā-yā", "3sg. pres."),
    "praviśet": ("should enter", "pra-viś", "3sg. opt."),

    # cognitive
    "vetti": ("knows", "vid", "3sg. pres."),
    "veda": ("knows", "vid", "3sg. pf./pres."),
    "vidyāt": ("would know", "vid", "3sg. opt."),
    "vetsi": ("you know", "vid", "2sg. pres."),
    "jānāti": ("knows", "jñā", "3sg. pres."),
    "paśyati": ("sees", "dṛś", "3sg. pres."),
    "stumaḥ": ("we praise", "stu", "1pl. pres."),

    # numbers
    "eka": ("one", "eka", "adj. stem"),
    "ekaḥ": ("one", "eka", "nom. sg. m."),
    "ekam": ("one", "eka", "nom./acc. sg. n."),
    "dvi": ("two", "dvi", "stem"),
    "dvau": ("two (m.)", "dvi", "nom. du. m."),
    "dve": ("two (f./n.)", "dvi", "nom. du. f./n."),
    "tri": ("three", "tri", "stem"),
    "trayam": ("triad", "traya", "nom./acc. sg. n."),
    "trīṇi": ("three (n.)", "tri", "nom./acc. pl. n."),
    "catur": ("four", "catur", "stem"),
    "catvāri": ("four (n.)", "catur", "nom./acc. pl. n."),
    "śata": ("hundred", "śata", "stem"),
    "śatam": ("a hundred", "śata", "nom./acc. sg. n."),

    # śrī / hari titles
    "śrī": ("blessed, illustrious; Śrī", "śrī", "stem"),
    "śrīdevy": ("the blessed Goddess", "śrīdevī", "nom. sg. f."),
    "śrīdevī": ("the blessed Goddess", "śrīdevī", "nom. sg. f."),
    "uvāca": ("said", "vac", "3sg. pf."),

    # specific Trika nouns commonly recurring
    "anugraha": ("grace", "anugraha", "stem"),
    "anugrahaḥ": ("grace", "anugraha", "nom. sg. m."),
    "nigraha": ("withdrawal, restraint", "nigraha", "stem"),
    "sthiti": ("maintenance, abiding", "sthiti", "stem"),
    "sthitiḥ": ("abiding, continuance", "sthiti", "nom. sg. f."),
    "srṣṭi": ("emission, creation", "sṛṣṭi", "stem"),
    "sṛṣṭi": ("emission, creation", "sṛṣṭi", "stem"),
    "sṛṣṭiḥ": ("creation, emission", "sṛṣṭi", "nom. sg. f."),
    "saṃhāra": ("dissolution, withdrawal", "saṃhāra", "stem"),
    "saṃhāraḥ": ("dissolution", "saṃhāra", "nom. sg. m."),
    "pralaya": ("dissolution", "pralaya", "stem"),
    "pralayaḥ": ("dissolution", "pralaya", "nom. sg. m."),
    "udaya": ("arising", "udaya", "stem"),
    "udayaḥ": ("arising", "udaya", "nom. sg. m."),
    "udayau": ("arising and...", "udaya", "nom. du. m."),
    "unmeṣa": ("opening, unfolding", "unmeṣa", "stem"),
    "nimeṣa": ("closing", "nimeṣa", "stem"),
    "avasthā": ("state, condition", "avasthā", "nom. sg. f."),
    "avasthāyām": ("in the state", "avasthā", "loc. sg. f."),
    "vyāpaka": ("all-pervading", "vyāpaka", "adj. stem"),
    "vyāpakatva": ("pervasiveness", "vyāpakatva", "stem"),
    "vyāpakatvāt": ("due to pervasiveness", "vyāpakatva", "abl. sg. n."),
    "vikalpa": ("conceptual construct, thought", "vikalpa", "stem"),
    "vikalpaḥ": ("thought-construct", "vikalpa", "nom. sg. m."),
    "vikalpāḥ": ("thought-constructs", "vikalpa", "nom. pl. m."),
    "vikalpānām": ("of thought-constructs", "vikalpa", "gen. pl. m."),
    "nirvikalpa": ("free of thought-constructs", "nirvikalpa", "adj."),
    "nirvikalpaḥ": ("thought-free", "nirvikalpa", "nom. sg. m."),
    "nirvikalpam": ("thought-free", "nirvikalpa", "nom./acc. sg. n."),
    "saṃkalpa": ("intention, willed-thought", "saṃkalpa", "stem"),
    "abheda": ("non-difference, unity", "abheda", "stem"),
    "abhedaḥ": ("non-difference", "abheda", "nom. sg. m."),
    "bheda": ("difference, division", "bheda", "stem"),
    "bhedaḥ": ("difference, division", "bheda", "nom. sg. m."),
    "advaita": ("non-dual", "advaita", "adj. stem"),
    "abhyāsa": ("repeated practice", "abhyāsa", "stem"),
    "saṃskāra": ("latent impression", "saṃskāra", "stem"),
    "ahaṃkāra": ("ego, I-maker", "ahaṃkāra", "stem"),

    # senses
    "rasa": ("taste, essence", "rasa", "stem"),
    "rasaḥ": ("taste, essence", "rasa", "nom. sg. m."),
    "gandha": ("smell", "gandha", "stem"),
    "rūpaḥ": ("form (m.)", "rūpa", "nom. sg. m."),
    "sparśa": ("touch", "sparśa", "stem"),
    "śravaṇa": ("hearing", "śravaṇa", "stem"),

    # mātṛkā / phoneme system
    "mātṛkā": ("the alphabet-goddess, the array of phonemes", "mātṛkā", "nom. sg. f."),
    "adhiṣṭhāna": ("substratum", "adhiṣṭhāna", "stem"),
    "adhiṣṭhānam": ("the substratum", "adhiṣṭhāna", "nom./acc. sg. n."),

    # body / nāḍī
    "nāḍī": ("channel", "nāḍī", "nom. sg. f."),
    "suṣumnā": ("the central channel", "suṣumnā", "nom. sg. f."),
    "kuṇḍalinī": ("the coiled energy", "kuṇḍalinī", "nom. sg. f."),
    "cakra": ("wheel, centre", "cakra", "stem"),
    "cakram": ("wheel", "cakra", "nom./acc. sg. n."),

    # affixes commonly tokenized alone
    "ity": ("thus (sandhi)", "iti", "ptcl."),
    "ity uktam": ("thus said", "iti vac", "phrase"),
    "ity ucyate": ("thus it is said", "iti vac", "phrase"),

    # Misc particles often dangling
    "sma": ("(past-marker ptcl.)", "sma", "ptcl."),
    "ha": ("(emphatic ptcl.)", "ha", "ptcl."),
}


# Build the normalized lookup
LEXICON: dict[str, tuple[str, str, str | None]] = {norm(k): v for k, v in _RAW.items()}


def lookup(token: str) -> tuple[str, str, str | None] | None:
    """Look up a token in the lexicon. Returns (gloss_en, lemma_iast, morph) or None."""
    n = norm(token)
    if not n:
        return None
    if n in LEXICON:
        return LEXICON[n]
    # strip leading sandhi marks
    if n.startswith("'"):
        return LEXICON.get(n.lstrip("'"))
    return None
