#!/usr/bin/env bun
/**
 * seo-scaffold-existing — one-shot retrofit helper.
 *
 * Reads each YAML in data/corpus/*.yaml that's MISSING a seo: block,
 * and APPENDS a commented-out seo: scaffold to the file. The curator
 * reviews + un-comments + edits per-locale descriptions + keywords.
 *
 * Usage:
 *   bun scripts/seo-scaffold-existing.ts                       # dry-run, print to stdout
 *   bun scripts/seo-scaffold-existing.ts --write               # write scaffolds to files
 *   bun scripts/seo-scaffold-existing.ts --text=siva-sutras    # one text only
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const CORPUS_DIR = 'data/corpus';
export const LANGS = [
  'en',
  'hi',
  'ta',
  'te',
  'bn',
  'mr',
  'gu',
  'kn',
  'ml',
  'pa',
  'or',
  'as',
] as const;

interface Args {
  write: boolean;
  textFilter?: string;
}

function parseArgs(): Args {
  const argv = process.argv.slice(2);
  return {
    write: argv.includes('--write'),
    textFilter: argv.find((a) => a.startsWith('--text='))?.split('=')[1],
  };
}

export function hasSeoBlock(yaml: string): boolean {
  return /^seo:/m.test(yaml);
}

export function hasSchemaVersion(yaml: string): boolean {
  return /^schema_version:/m.test(yaml);
}

export function buildScaffold(slug: string): string {
  const descLines = LANGS.map(
    (lang) =>
      `#     ${lang}: ""  # TODO: 140-160 char native-script ${lang} description for ${slug}`,
  ).join('\n');
  const kwLines = LANGS.map(
    (lang) => `#     ${lang}: []  # TODO: 3-6 ${lang} keywords (native script for non-en)`,
  ).join('\n');
  return `
# ─── seo: block scaffold (auto-generated by scripts/seo-scaffold-existing.ts) ──
# Review each per-locale description. Use native script (no English in Hindi field).
# Uncomment the block + fill in once reviewed. Then delete this comment header.
# schema_version: 1
# seo:
#   descriptions:
${descLines}
#   keywords:
${kwLines}
#   noindex_langs: []  # populate with langs where AI translation quality is suspect
# ──────────────────────────────────────────────────────────────────────────────
`;
}

function main(): void {
  const args = parseArgs();
  const files = readdirSync(CORPUS_DIR)
    .filter((f) => f.endsWith('.yaml') && !f.startsWith('_'))
    .filter((f) => !args.textFilter || f.includes(args.textFilter));

  let scaffoldedCount = 0;
  let skippedCount = 0;

  for (const file of files) {
    const path = join(CORPUS_DIR, file);
    const yaml = readFileSync(path, 'utf8');
    if (hasSeoBlock(yaml)) {
      console.log(`SKIP  ${file}  (already has seo: block)`);
      skippedCount++;
      continue;
    }
    const slug = file.replace('.yaml', '');
    const scaffold = buildScaffold(slug);
    if (args.write) {
      writeFileSync(path, `${yaml.trimEnd()}\n${scaffold}\n`);
      console.log(`WROTE ${file}`);
    } else {
      console.log(`---- DRY-RUN for ${file} ----`);
      console.log(scaffold);
    }
    scaffoldedCount++;
  }

  console.log(`\nDone. Scaffolded: ${scaffoldedCount}, Skipped: ${skippedCount}.`);
  if (!args.write) {
    console.log(`Re-run with --write to append the scaffolds to files.`);
  }
  if (scaffoldedCount > 0 && args.write) {
    console.log(
      `Next: edit each scaffolded file, fill in per-locale descriptions/keywords, uncomment.`,
    );
  }
}

// Only execute main when invoked as a script (not when imported by tests).
const invokedDirectly =
  typeof process !== 'undefined' &&
  Array.isArray(process.argv) &&
  process.argv[1] &&
  process.argv[1].endsWith('seo-scaffold-existing.ts');

if (invokedDirectly) {
  main();
}
